### ISSUE TITLE
Panic occurred  when using `ForEach`

### ISSUE THREAD

**Issue by cheung-chifung** [etcd-io/bbolt#106]
# Issue

My application crashed and printed following logs when I restart the process. 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf5ab3d]

goroutine 222450 [running]:
MYVENDOR/github.com/coreos/bbolt.(*DB).page(...)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/db.go:859
MYVENDOR/github.com/coreos/bbolt.(*Tx).page(...)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/tx.go:599
MYVENDOR/github.com/coreos/bbolt.(*Bucket).pageNode(0xc42525ee80, 0x1318, 0xa, 0x0)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/bucket.go:724 +0xad
MYVENDOR/github.com/coreos/bbolt.(*Cursor).first(0xc4251f9e90)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/cursor.go:187 +0x9c
MYVENDOR/github.com/coreos/bbolt.(*Cursor).next(0xc4251f9e90, 0x141e917, 0x9, 0x0, 0x0, 0x0, 0x0, 0xffffffffffffffff)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/cursor.go:240 +0x8b
MYVENDOR/github.com/coreos/bbolt.(*Cursor).Next(0xc4251f9e90, 0x2d, 0x2d, 0x7f542e7aca22, 0x8e, 0x8e, 0x0)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/cursor.go:75 +0x71
MYVENDOR/github.com/coreos/bbolt.(*Bucket).ForEach(0xc42525ee80, 0xc4251f9ef8, 0x8, 0x8)
        /MYGOPATH/src/MYVENDOR/github.com/coreos/bbolt/bucket.go:387 +0xbf
```

What I did was just use `ForEach` in `View`, here is the pseudo code:

```
		err := s.db.View(func(tx *bolt.Tx) error {
			bts := tx.Bucket(myBucketName)
			return bts.ForEach(func(k []byte, v []byte) error {
                                  // here is  my code
                          }
                  })
```

When I restart the process one more time, panic is gone and everything works perfectly. I also have a simple tool for dumping my database into JSON file,  and the DB also looks like intact.

Other application logs tell me it may be a race condition conflict bug. I would post more details if I got more information.

# Version

af9db2027c98c61ecd8e17caa5bd265792b9b9a2

**Comment by bharathramh92** [comment]
You need to copy your byte data from the db context and return it. Checkout the last line in https://github.com/coreos/bbolt#using-keyvalue-pairs

**Comment by ahrtr** [comment]
It is the application's issue.
