### ISSUE TITLE
panic: invalid page type with tx.Bucket() (or any read operation)

### ISSUE THREAD

**Issue by zwass** [etcd-io/bbolt#128]
It's not possible to perform any read operations on this DB as the Bolt library panics. Note, this DB was created with boltdb/bolt, and crashes on both that and this fork.

Unfortunately I cannot share the DB contents for privacy reasons.

```
panic: invalid page type: 83597: 10

goroutine 1 [running]:
go.etcd.io/bbolt.(*Cursor).search(0xc000078df0, 0xc000078e88, 0x6, 0x20, 0x1468d)
	/Users/zwass/dev/go/src/go.etcd.io/bbolt/cursor.go:250 +0x371
go.etcd.io/bbolt.(*Cursor).seek(0xc000078df0, 0xc000078e88, 0x6, 0x20, 0x0, 0x0, 0x0, 0xc000078e08, 0x103b8b1, 0xc000086020, ...)
	/Users/zwass/dev/go/src/go.etcd.io/bbolt/cursor.go:159 +0xa5
go.etcd.io/bbolt.(*Bucket).Bucket(0xc0000a0018, 0xc000078e88, 0x6, 0x20, 0xc000078e88)
	/Users/zwass/dev/go/src/go.etcd.io/bbolt/bucket.go:105 +0xe6
go.etcd.io/bbolt.(*Tx).Bucket(0xc0000a0000, 0xc000078e88, 0x6, 0x20, 0x6)
	/Users/zwass/dev/go/src/go.etcd.io/bbolt/tx.go:101 +0x4f
main.main.func1(0xc0000a0000, 0x10ea340, 0xc0000a0000)
	/Users/zwass/dev/test.go:17 +0x6c
go.etcd.io/bbolt.(*DB).View(0xc000096000, 0x10ea378, 0x0, 0x0)
	/Users/zwass/dev/go/src/go.etcd.io/bbolt/db.go:701 +0x90
main.main()
	/Users/zwass/dev/test.go:16 +0x111
exit status 2

```

```
package main

import (
	"log"

	bolt "go.etcd.io/bbolt"
)

func main() {
	db, err := bolt.Open("/Users/zwass/Downloads/launcher.db", 0600, &bolt.Options{ReadOnly: true})
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	db.View(func(tx *bolt.Tx) error {
		tx.Bucket([]byte("foobar"))
		return nil
	})
}

```

**Comment by ahrtr** [comment]
> panic: invalid page type: 83597: 10

0x10 is the flag for freelist page. It means the freelist page was somehow in the tree
