### ISSUE TITLE
page already freed after unclean close

### ISSUE THREAD

**Issue by magik6k** [etcd-io/bbolt#266]
I had a boltdb become corrupted after the application was killed on OOM, now it panics with
```
panic: page 1364595 already freed

goroutine 1 [running]:
go.etcd.io/bbolt.(*freelist).free(0xc00011c000, 0x2aca01, 0x7f938e4a4000)
        /home/magik6k/.opt/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/freelist.go:175 +0x3e7
go.etcd.io/bbolt.(*node).spill(0xc000098000, 0x10, 0x10)
        /home/magik6k/.opt/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/node.go:359 +0x405
go.etcd.io/bbolt.(*Bucket).spill(0xc00017e018, 0xbad2bc4, 0x5a6aa0)
        /home/magik6k/.opt/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/bucket.go:570 +0x49a
go.etcd.io/bbolt.(*Tx).Commit(0xc00017e000, 0x0, 0x0)
        /home/magik6k/.opt/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/tx.go:160 +0xe8
go.etcd.io/bbolt.(*DB).Update(0xc000196000, 0xc000195f58, 0x0, 0x0)
        /home/magik6k/.opt/go/pkg/mod/go.etcd.io/bbolt@v1.3.5/db.go:701 +0x105
main.main()
        /home/magik6k/github.com/filecoin-project/go-lotus/bopen.go:15 +0xe5
exit status 2
```

Opening with this bit of code:
```
package main

import (
	bolt "go.etcd.io/bbolt"
	"golang.org/x/xerrors"
)

func main() {
	db, err := bolt.Open("tracker.bolt", 0644, nil)
	if err != nil {
		panic(err)
	}

	bucketId := []byte("tracker")
	err = db.Update(func(tx *bolt.Tx) error { // Panic here
		_, err := tx.CreateBucketIfNotExists(bucketId)
		if err != nil {
			return xerrors.Errorf("error creating bolt db bucket %s: %w", string(bucketId), err)
		}
		return nil
	})

	if err != nil {
		_ = db.Close()
		panic(err)
	}
}
```

The main application was setting
```
opts := &bolt.Options{
	Timeout: 1 * time.Second,
	NoSync:  true,
}
```

While I'd expect to lose some data on unclean shutdown with nosync, it should still be possible to open the store, or at the very least get an error instead of a panic, so it can be handled more gracefully.

Corrupted bolt file (just public blockchain metadata, ~11G) - https://ipfs.io/ipfs/QmZ9HFaDt29YX67M5gJF6gbKYxGcRwHxCGda2DBERK4EMx/tracker.bolt

**Comment by ydcool** [comment]
any update here? we've the same issue.

**Comment by tmm1** [comment]
I see similar issues on some instances sometimes after an unclean shutdown.

```
page 219 already freed
  File "go.etcd.io/bbolt@v1.3.6/freelist.go", line 175, in go.etcd.io/bbolt.(*freelist).free
  File "go.etcd.io/bbolt@v1.3.6/node.go", line 359, in go.etcd.io/bbolt.(*node).spill
  File "go.etcd.io/bbolt@v1.3.6/node.go", line 346, in go.etcd.io/bbolt.(*node).spill
  File "go.etcd.io/bbolt@v1.3.6/bucket.go", line 570, in go.etcd.io/bbolt.(*Bucket).spill
  File "go.etcd.io/bbolt@v1.3.6/bucket.go", line 537, in go.etcd.io/bbolt.(*Bucket).spill
  File "go.etcd.io/bbolt@v1.3.6/tx.go", line 160, in go.etcd.io/bbolt.(*Tx).Commit
  File "go.etcd.io/bbolt@v1.3.6/db.go", line 756, in go.etcd.io/bbolt.(*DB).Update

```

**Comment by ptabor** [comment]
Please explore the structure using `./bbolt page --all --format-value=redacted`. 

NoSync means that strange things can happen and random pages might be 'stale'. Bbolt is not prepared to handle that gracefully.   Please don''t use no-sync apart of 'testing' environments when clean retry from no-state  in an automated option.
