### ISSUE TITLE
Crash by: signal SIGBUS: bus error

### ISSUE THREAD

**Issue by itayronen** [etcd-io/bbolt#286]
The program crashed due to memory access violation.
The journalctl:
```
Jul 26 14:51:00 machine server[000]: [signal SIGBUS: bus error code=0x2 addr=0x7fae72f5d008 pc=0x15de345]
Jul 26 14:51:00 machine server[000]: goroutine 1364 [running]:
Jul 26 14:51:00 machine server[000]: runtime.throw(0x3075a67, 0x5)
Jul 26 14:51:00 machine server[000]: /usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0004b4b58 sp=0xc0004b4b28 pc=0x43a2f2
Jul 26 14:51:00 machine server[000]: runtime.sigpanic()
Jul 26 14:51:00 machine server[000]: /usr/local/go/src/runtime/signal_unix.go:731 +0x2c8 fp=0xc0004b4b90 sp=0xc0004b4b58 pc=0x451868
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).search(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x14ef5d)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:249 +0x65 fp=0xc0004b4c28 sp=0xc0004b4b90 pc=0x15de345
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).searchPage(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x7fad3f929000)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:308 +0x15f fp=0xc0004b4cb8 sp=0xc0004b4c28 pc=0x15de8ff
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).search(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x1b929)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:265 +0x194 fp=0xc0004b4d50 sp=0xc0004b4cb8 pc=0x15de474
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).searchPage(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x7fad5fd13000)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:308 +0x15f fp=0xc0004b4de0 sp=0xc0004b4d50 pc=0x15de8ff
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).search(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x3bd13)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:265 +0x194 fp=0xc0004b4e78 sp=0xc0004b4de0 pc=0x15de474
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Cursor).seek(0xc0004b4f58, 0x7fae274f90e6, 0xd, 0xd, 0x7f9cbf78cd10, 0x8, 0x8, 0x7faee1b431d8, 0x8, 0xc005366b58, ...)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/cursor.go:159 +0x7d fp=0xc0004b4ee8 sp=0xc0004b4e78 pc=0x15ddbfd
Jul 26 14:51:00 machine server[000]: github.com/etcd-io/bbolt.(*Bucket).Get(0xc0006ed240, 0x7fae274f90e6, 0xd, 0xd, 0x17, 0xc0006ed240, 0xc0006ed240)
Jul 26 14:51:00 machine server[000]: /builds/gopath/pkg/mod/github.com/etcd-io/bbolt@v0.0.0-20190809044356-35b666109344/bucket.go:260 +0xbb fp=0xc0004b4f88 sp=0xc0004b4ee8 pc=0x15daa9b
... Our code
```

On our code we opened a `View` on the bucked, `ForEach` on it, then for some weird reason called `Get(key)` even though we have the value from the `ForEach`.
Anyway this code works for 99.9% of the times but suddenly we encountered this memory violation.

**Comment by ahrtr** [comment]
It's most likely is that the db file is corrupted. 

I fixed a similar issue before, please see [13406](https://github.com/ahrtr/etcd-issues/tree/master/13406) If you can provide the db file and let me know the etcd version, then I can take a look.

**Comment by itayronen** [comment]
Correct we actually got to the same conclusion and I didn't update, sorry for that.
