### ISSUE TITLE
runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by 0ZeroCN** [etcd-io/bbolt#576]
panic: runtime error: slice bounds out of range [::4326323766] with length 21474
83647

goroutine 1 [running]:
go.etcd.io/bbolt.unsafeByteSlice(...)
        H:/m/Server/vendor/go.etcd.io/bbolt/unsafe.go:27
go.etcd.io/bbolt.(*leafPageElement).key(...)
        H:/m/Server/vendor/go.etcd.io/bbolt/page.go:126
go.etcd.io/bbolt.(*Cursor).nsearch.func2(0xc000429f80?)
        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:328 +0x92
sort.Search(0x1940598?, 0xc0005177f0)
        D:/Program Files/Go/src/sort/search.go:65 +0x46
go.etcd.io/bbolt.(*Cursor).nsearch(0xc000016060?, {0x11b61e8?, 0xc00004e000?, 0x
9384d9?})
        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:327 +0xf4
go.etcd.io/bbolt.(*Cursor).search(0xc000517ab8, {0x11b61e8, 0x5, 0x5}, 0x0?)
        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:257 +0x1ee
go.etcd.io/bbolt.(*Cursor).searchPage(0xc000517ab8, {0x11b61e8, 0x5, 0x5}, 0xbb8
ee0?)
        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:308 +0x15a
go.etcd.io/bbolt.(*Cursor).search(0xc000517ab8, {0x11b61e8, 0x5, 0x5}, 0x100c000
517a48?)
        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:265 +0x1c5
go.etcd.io/bbolt.(*Cursor).seek(0xc000517ab8, {0x11b61e8?, 0x0?, 0xc000517af0?})

        H:/m/Server/vendor/go.etcd.io/bbolt/cursor.go:159 +0x45
go.etcd.io/bbolt.(*Bucket).Bucket(0xc0000b27f8, {0x11b61e8, 0x5, 0xc0000f51a0?})

        H:/m/Server/vendor/go.etcd.io/bbolt/bucket.go:105 +0xb2
go.etcd.io/bbolt.(*Tx).Bucket(...)
        H:/m/Server/vendor/go.etcd.io/bbolt/tx.go:101
local.dev/nightsky/db.ReadUser.func1(0x30?)

**Comment by 0ZeroCN** [comment]
go.etcd.io/bbolt v1.3.6

**Comment by ahrtr** [comment]
thx @0ZeroCN for raising this issue. Is it possible the share the db file so that I can take a closer look?

**Comment by 0ZeroCN** [comment]
The database file size is 4G, which is too large. I have no problem creating a new database.

**Comment by 0ZeroCN** [comment]
I'm just upgrading the program, but restoring to the old program doesn't have this problem.The code has not been modified, just upgrading go.exe to the latest version.
