### ISSUE TITLE
Possible Runtime Error (Potential Deadlock) and Incorrect Results Under High Concurrency with NoSync Enabled

### ISSUE THREAD

**Issue by youngk1019** [etcd-io/bbolt#618]
When operating under high concurrency conditions with the NoSync option enabled, there is a possibility of encountering a runtime error, which could be indicative of a deadlock. Additionally, this scenario may lead to incorrect results being produced.

Below is the test code:

```go
package main

import (
	"crypto/rand"
	"errors"
	"github.com/stretchr/testify/assert"
	"go.etcd.io/bbolt"
	"path"
	"strconv"
	"sync"
	"testing"
)

var ErrKeyNotFound = errors.New("key not found")

type Store struct {
	db     *bbolt.DB
	bucket []byte
}

func NewStore(path string, bucket []byte) (*Store, error) {
	dbOpt := bbolt.DefaultOptions
	dbOpt.NoSync = true
	db, err := bbolt.Open(path, 0600, dbOpt)
	if err != nil {
		return nil, err
	}
	err = db.Update(func(txn *bbolt.Tx) error {
		_, err := txn.CreateBucketIfNotExists(bucket)
		return err
	})
	if err != nil {
		return nil, err
	}
	return &Store{
		db:     db,
		bucket: bucket,
	}, nil
}

func (s *Store) Put(key []byte, val []byte) error {
	return s.db.Update(func(txn *bbolt.Tx) error {
		return txn.Bucket(s.bucket).Put(key, val)
	})
}

func (s *Store) Get(key []byte) ([]byte, error) {
	var val []byte
	return val, s.db.View(func(txn *bbolt.Tx) error {
		b := txn.Bucket(s.bucket)
		val = b.Get(key)
		if val == nil {
			return ErrKeyNotFound
		}
		return nil
	})
}

func (s *Store) Delete(key []byte) error {
	return s.db.Update(func(txn *bbolt.Tx) error {
		return txn.Bucket(s.bucket).Delete(key)
	})
}

func TestBBolt(t *testing.T) {
	dir := t.TempDir()
	store, err := NewStore(path.Join(dir, "bbolt.db"), []byte("test"))
	assert.Equal(t, nil, err)
	wg := &sync.WaitGroup{}
	val := make([]byte, 64)
	_, _ = rand.Read(val)
	for i := 1; i < 1024; i++ {
		i := i
		wg.Add(1)
		go func() {
			defer wg.Done()
			key := []byte(strconv.Itoa(i))
			v, err := store.Get(key)
			assert.Equal(t, ErrKeyNotFound, err)
			assert.Nil(t, v)

			err = store.Put(key, val)
			assert.Nil(t, err)

			v, err = store.Get(key)
			assert.Nil(t, err)
			assert.Equal(t, val, v)

			err = store.Delete(key)
			assert.Nil(t, err)

			v, err = store.Get(key)
			assert.Equal(t, ErrKeyNotFound, err)
			assert.Nil(t, v)
		}()
	}
	wg.Wait()
}

```

For this test case, there may be three possible outcomes:
the first is a successful test：
```bash
=== RUN   TestBBolt
--- PASS: TestBBolt (0.11s)
PASS
```

the second is a runtime error, some of the error messages are as follows:
```bash
goroutine 462 [sync.Mutex.Lock]:
runtime.gopark(0x14000276cd8?, 0x10450af24?, 0x0?, 0x1a?, 0x14000276cf8?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000276ca0 sp=0x14000276c80 pc=0x1044ed9a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:404
runtime.semacquire1(0x1400015287c, 0x7d?, 0x3, 0x1, 0xa?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:160 +0x208 fp=0x14000276cf0 sp=0x14000276ca0 pc=0x1044ff9d8
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:77 +0x28 fp=0x14000276d30 sp=0x14000276cf0 pc=0x10451c728
sync.(*Mutex).lockSlow(0x14000152878)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:171 +0x174 fp=0x14000276d80 sp=0x14000276d30 pc=0x104526e54
sync.(*Mutex).Lock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0x140001526c0)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:779 +0x98 fp=0x14000276e00 sp=0x14000276d80 pc=0x10465e048
go.etcd.io/bbolt.(*DB).Begin(0x14000276e88?, 0xd4?)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:721 +0x20 fp=0x14000276e20 sp=0x14000276e00 pc=0x10465dbb0
go.etcd.io/bbolt.(*DB).Update(0x10473b1f8?, 0x14000276f80)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:870 +0x30 fp=0x14000276e90 sp=0x14000276e20 pc=0x10465e870
code.(*Store).Put(...)
	/Users/youngk/go/src/code/bbolt_test.go:42
code.TestBBolt.func1()
	/Users/youngk/go/src/code/bbolt_test.go:82 +0x1a8 fp=0x14000276fd0 sp=0x14000276e90 pc=0x10466ab38
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000276fd0 sp=0x14000276fd0 pc=0x104520ac4
created by code.TestBBolt in goroutine 6
	/Users/youngk/go/src/code/bbolt_test.go:75 +0x110

goroutine 463 [sync.Mutex.Lock]:
runtime.gopark(0x14000277cd8?, 0x10450af24?, 0x0?, 0x1a?, 0x14000277cf8?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:398 +0xc8 fp=0x14000277ca0 sp=0x14000277c80 pc=0x1044ed9a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:404
runtime.semacquire1(0x1400015287c, 0x7d?, 0x3, 0x1, 0xf2?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:160 +0x208 fp=0x14000277cf0 sp=0x14000277ca0 pc=0x1044ff9d8
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:77 +0x28 fp=0x14000277d30 sp=0x14000277cf0 pc=0x10451c728
sync.(*Mutex).lockSlow(0x14000152878)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:171 +0x174 fp=0x14000277d80 sp=0x14000277d30 pc=0x104526e54
sync.(*Mutex).Lock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0x140001526c0)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:779 +0x98 fp=0x14000277e00 sp=0x14000277d80 pc=0x10465e048
go.etcd.io/bbolt.(*DB).Begin(0x14000277e88?, 0xd4?)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:721 +0x20 fp=0x14000277e20 sp=0x14000277e00 pc=0x10465dbb0
go.etcd.io/bbolt.(*DB).Update(0x10473b1f8?, 0x14000277f80)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:870 +0x30 fp=0x14000277e90 sp=0x14000277e20 pc=0x10465e870
code.(*Store).Put(...)
	/Users/youngk/go/src/code/bbolt_test.go:42
code.TestBBolt.func1()
	/Users/youngk/go/src/code/bbolt_test.go:82 +0x1a8 fp=0x14000277fd0 sp=0x14000277e90 pc=0x10466ab38
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x14000277fd0 sp=0x14000277fd0 pc=0x104520ac4
created by code.TestBBolt in goroutine 6
	/Users/youngk/go/src/code/bbolt_test.go:75 +0x110

goroutine 464 [sync.Mutex.Lock]:
runtime.gopark(0x1400052ccd8?, 0x10450af24?, 0x0?, 0x1a?, 0x1400052ccf8?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:398 +0xc8 fp=0x1400052cca0 sp=0x1400052cc80 pc=0x1044ed9a8
runtime.goparkunlock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/proc.go:404
runtime.semacquire1(0x1400015287c, 0x7d?, 0x3, 0x1, 0xf7?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:160 +0x208 fp=0x1400052ccf0 sp=0x1400052cca0 pc=0x1044ff9d8
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/sema.go:77 +0x28 fp=0x1400052cd30 sp=0x1400052ccf0 pc=0x10451c728
sync.(*Mutex).lockSlow(0x14000152878)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:171 +0x174 fp=0x1400052cd80 sp=0x1400052cd30 pc=0x104526e54
sync.(*Mutex).Lock(...)
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/sync/mutex.go:90
go.etcd.io/bbolt.(*DB).beginRWTx(0x140001526c0)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:779 +0x98 fp=0x1400052ce00 sp=0x1400052cd80 pc=0x10465e048
go.etcd.io/bbolt.(*DB).Begin(0x1400052ce88?, 0xd4?)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:721 +0x20 fp=0x1400052ce20 sp=0x1400052ce00 pc=0x10465dbb0
go.etcd.io/bbolt.(*DB).Update(0x10473b1f8?, 0x1400052cf80)
	/Users/youngk/go/pkg/mod/go.etcd.io/bbolt@v1.3.8/db.go:870 +0x30 fp=0x1400052ce90 sp=0x1400052ce20 pc=0x10465e870
code.(*Store).Put(...)
	/Users/youngk/go/src/code/bbolt_test.go:42
code.TestBBolt.func1()
	/Users/youngk/go/src/code/bbolt_test.go:82 +0x1a8 fp=0x1400052cfd0 sp=0x1400052ce90 pc=0x10466ab38
runtime.goexit()
	/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197 +0x4 fp=0x1400052cfd0 sp=0x1400052cfd0 pc=0x104520ac4
created by code.TestBBolt in goroutine 6
	/Users/youngk/go/src/code/bbolt_test.go:75 +0x110
```
and the third is incorrect results:
```bash
=== RUN   TestBBolt
    bbolt_test.go:87: 
        	Error Trace:	/Users/youngk/go/src/code/bbolt_test.go:87
        	            				/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Not equal: 
        	            	expected: []byte{0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27, 0xc0, 0x75, 0x8e, 0xa, 0x81, 0xaa, 0xe4, 0xa7, 0xc0, 0x93, 0xa2, 0x40, 0xb1, 0xef, 0xcf, 0xda, 0xcb, 0xfe, 0x96, 0x23, 0x3d, 0x2f, 0x4d, 0x6, 0x8d, 0xe9, 0x7d, 0x5f, 0xd3, 0x6d, 0x65, 0x81, 0x5a, 0x55, 0xc8, 0x35}
        	            	actual  : []byte{0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0xc8, 0x35, 0x32, 0x33, 0x31, 0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27, 0xc0, 0x75, 0x8e, 0xa, 0x81, 0xaa, 0xe4}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,6 +1,6 @@
        	            	 ([]uint8) (len=64) {
        	            	- 00000000  8b 31 be ba 73 45 c2 82  96 61 81 76 44 8a 84 39  |.1..sE...a.vD..9|
        	            	- 00000010  a5 a3 05 64 5b e3 65 cf  72 18 88 27 c0 75 8e 0a  |...d[.e.r..'.u..|
        	            	- 00000020  81 aa e4 a7 c0 93 a2 40  b1 ef cf da cb fe 96 23  |.......@.......#|
        	            	- 00000030  3d 2f 4d 06 8d e9 7d 5f  d3 6d 65 81 5a 55 c8 35  |=/M...}_.me.ZU.5|
        	            	+ 00000000  ba 73 45 c2 82 96 61 81  76 44 8a 84 39 a5 a3 05  |.sE...a.vD..9...|
        	            	+ 00000010  64 5b e3 65 cf 72 18 88  27 c0 75 8e 0a 81 aa e4  |d[.e.r..'.u.....|
        	            	+ 00000020  a7 c0 93 a2 40 b1 ef cf  da cb fe 96 23 3d 2f 4d  |....@.......#=/M|
        	            	+ 00000030  06 8d e9 7d 5f d3 6d 65  81 5a 55 c8 35 32 33 32  |...}_.me.ZU.5232|
        	            	 }
        	Test:       	TestBBolt
    bbolt_test.go:87: 
        	Error Trace:	/Users/youngk/go/src/code/bbolt_test.go:87
        	            				/opt/homebrew/Cellar/go/1.21.4/libexec/src/runtime/asm_arm64.s:1197
        	Error:      	Not equal: 
        	            	expected: []byte{0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27, 0xc0, 0x75, 0x8e, 0xa, 0x81, 0xaa, 0xe4, 0xa7, 0xc0, 0x93, 0xa2, 0x40, 0xb1, 0xef, 0xcf, 0xda, 0xcb, 0xfe, 0x96, 0x23, 0x3d, 0x2f, 0x4d, 0x6, 0x8d, 0xe9, 0x7d, 0x5f, 0xd3, 0x6d, 0x65, 0x81, 0x5a, 0x55, 0xc8, 0x35}
        	            	actual  : []byte{0x7d, 0x5f, 0xd3, 0x6d, 0x65, 0x81, 0x5a, 0x55, 0xc8, 0x35, 0x38, 0x32, 0x32, 0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27, 0xc0, 0x75, 0x8e, 0xa, 0x81, 0xaa, 0xe4, 0xa7, 0xc0, 0x93, 0xa2, 0x40, 0xb1, 0xef, 0xcf, 0xda, 0xcb, 0xfe, 0x96, 0x23, 0x3d, 0x2f, 0x4d}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,6 +1,6 @@
        	            	 ([]uint8) (len=64) {
        	            	- 00000000  8b 31 be ba 73 45 c2 82  96 61 81 76 44 8a 84 39  |.1..sE...a.vD..9|
        	            	- 00000010  a5 a3 05 64 5b e3 65 cf  72 18 88 27 c0 75 8e 0a  |...d[.e.r..'.u..|
        	            	- 00000020  81 aa e4 a7 c0 93 a2 40  b1 ef cf da cb fe 96 23  |.......@.......#|
        	            	- 00000030  3d 2f 4d 06 8d e9 7d 5f  d3 6d 65 81 5a 55 c8 35  |=/M...}_.me.ZU.5|
        	            	+ 00000000  7d 5f d3 6d 65 81 5a 55  c8 35 38 32 32 8b 31 be  |}_.me.ZU.5822.1.|
        	            	+ 00000010  ba 73 45 c2 82 96 61 81  76 44 8a 84 39 a5 a3 05  |.sE...a.vD..9...|
        	            	+ 00000020  64 5b e3 65 cf 72 18 88  27 c0 75 8e 0a 81 aa e4  |d[.e.r..'.u.....|
        	            	+ 00000030  a7 c0 93 a2 40 b1 ef cf  da cb fe 96 23 3d 2f 4d  |....@.......#=/M|
        	            	 }
        	Test:       	TestBBolt
--- FAIL: TestBBolt (0.09s)


Expected :[]byte{0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27, 0xc0, 0x75, 0x8e, 0xa, 0x81, 0xaa, 0xe4, 0xa7, 0xc0, 0x93, 0xa2, 0x40, 0xb1, ...

Actual   :[]byte{0x7d, 0x5f, 0xd3, 0x6d, 0x65, 0x81, 0x5a, 0x55, 0xc8, 0x35, 0x38, 0x32, 0x32, 0x8b, 0x31, 0xbe, 0xba, 0x73, 0x45, 0xc2, 0x82, 0x96, 0x61, 0x81, 0x76, 0x44, 0x8a, 0x84, 0x39, 0xa5, 0xa3, 0x5, 0x64, 0x5b, 0xe3, 0x65, 0xcf, 0x72, 0x18, 0x88, 0x27 ...

<Click to see difference>


FAIL
```
For the third scenario, when tested multiple times under version go1.21.2, this issue did not occur. However, it emerged under version go1.21.4. Of course, this might simply be due to not having triggered the third scenario previously due to bad luck, and it may not be related to the version of Go.

My bbolt version is:
go.etcd.io/bbolt v1.3.8

My Go environment is:
```bash
GO111MODULE='auto'
GOARCH='arm64'
GOBIN='/Users/youngk/go/bin'
GOCACHE='/Users/youngk/Library/Caches/go-build'
GOENV='/Users/youngk/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='arm64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/youngk/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/youngk/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/opt/homebrew/Cellar/go/1.21.4/libexec'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/opt/homebrew/Cellar/go/1.21.4/libexec/pkg/tool/darwin_arm64'
GOVCS=''
GOVERSION='go1.21.4'
GCCGO='gccgo'
AR='ar'
CC='cc'
CXX='c++'
CGO_ENABLED='1'
GOMOD=''
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch arm64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/rk/w1ng9jsx1kq5y6njq26x44nm0000gn/T/go-build3781692644=/tmp/go-build -gno-record-gcc-switches -fno-common'
```

**Comment by fuweid** [comment]
Hi @youngk1019 would you mind to try to copy value in Get api? The page can be changed because there are a lot of update request here. Thanks

**Comment by ahrtr** [comment]
FYI. https://github.com/etcd-io/bbolt#using-keyvalue-pairs

> Please note that values returned from Get() are only valid while the transaction is open. If you need to use a value outside of the transaction then you must use copy() to copy it to another byte slice.

Please reopen this issue if you still be able to reproduce this issue after copying the value returned by `bucket.Get`

**Comment by youngk1019** [comment]
Sorry, I did not notice the prompt in the document. The modified result meets expectations. Because the results of each test were different and there was an error message in the lock competition, I did not pay attention to it

**Comment by fuweid** [comment]
@youngk1019 no need to wrong about this. Thanks for filing issue. We can consider to highlight the limitation in the README.
